// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as RimbleUi from "rimble-ui";
import * as Styles$WildCards from "../../Styles.bs.js";
import * as Globals$WildCards from "../../harberger-lib/Globals.bs.js";
import * as RootProvider$WildCards from "../../harberger-lib/RootProvider.bs.js";
import * as MonthlyContribution$WildCards from "../Leaderboards/MonthlyContribution.bs.js";

var gorillaOnVine = "/img/wildcardsimages/gorilla-on-vine.png";

function HomepageLeaderBoard(Props) {
  var clearAndPush = RootProvider$WildCards.useClearNonUrlStateAndPushRoute(undefined);
  return React.createElement(RimbleUi.Box, {
              children: React.createElement(RimbleUi.Flex, {
                    children: null,
                    flexWrap: "wrap"
                  }, React.createElement(RimbleUi.Box, {
                        children: React.createElement("img", {
                              src: gorillaOnVine,
                              width: "100%"
                            }),
                        width: [0.28],
                        className: Styles$WildCards.animalImage
                      }), React.createElement(RimbleUi.Box, {
                        children: React.createElement(RimbleUi.Card, {
                              className: Styles$WildCards.infoCardStyles,
                              children: null
                            }, React.createElement(MonthlyContribution$WildCards.make, {
                                  numberOfLeaders: 6
                                }), React.createElement("br", undefined), React.createElement(RimbleUi.Box, {
                                  children: React.createElement(RimbleUi.Button, {
                                        className: Styles$WildCards.centerItemsMargin,
                                        children: Globals$WildCards.restr("View Other Leaderboards"),
                                        onClick: (function (e) {
                                            e.preventDefault();
                                            return Curry._1(clearAndPush, "/#leaderboards/monthly-contribution");
                                          })
                                      }),
                                  width: [1]
                                })),
                        width: [
                          1,
                          1,
                          0.59
                        ],
                        className: Styles$WildCards.infoCardContainer
                      })),
              className: Styles$WildCards.infoBackground
            });
}

var make = HomepageLeaderBoard;

export {
  gorillaOnVine ,
  make ,
  
}
/* react Not a pure module */
