// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Connectors from "./connectors";
import Web3CustomRoot from "./web3CustomRoot";

var injected = Connectors.injected;

var make = Web3CustomRoot;

var Custom = {
  make: make
};

export {
  injected ,
  Custom ,
  
}
/* injected Not a pure module */
