// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as $$String from "bs-platform/lib/es6/string.js";
import * as MomentRe from "bs-moment/src/MomentRe.js";
import * as Caml_format from "bs-platform/lib/es6/caml_format.js";

function isPositiveStringInteger(str) {
  var f = /^([0-9]\d*)$/;
  return f.test(str);
}

function elipsify(inputString, maxLength) {
  if (inputString.length > maxLength) {
    return $$String.sub("" + (String(inputString) + ""), 0, maxLength - 3 | 0) + "...";
  } else {
    return inputString;
  }
}

function bnToMoment(bn) {
  return MomentRe.momentWithUnix(Caml_format.caml_int_of_string(bn.toString()));
}

export {
  isPositiveStringInteger ,
  elipsify ,
  bnToMoment ,
  
}
/* MomentRe Not a pure module */
